extends RefCounted
## Credits shown on the Credits screen, grouped by where the work is used.
## Wording, licences and notes are copied verbatim from "res://docs/Credits.md".

const SECTIONS := [
	{
		"title": "Development Team",
		"entries": [
			{
				"name": "Muhammed Turhan",
				"creator": "",
				"license": "",
				"note": "",
				"links": ["https://www.linkedin.com/in/muhammed-turhan/"],
			},
			{
				"name": "Reyyan Pak",
				"creator": "",
				"license": "",
				"note": "",
				"links": ["https://www.linkedin.com/in/reyyan-pak-80b168297/"],
			},
			{
				"name": "Emelie Meinhardt",
				"creator": "",
				"license": "",
				"note": "",
				"links": ["https://emeliejoline.itch.io/"],
			},
		],
	},
	{
		"title": "Environment & Furniture",
		"entries": [
			{
				"name": "Top Down House",
				"creator": "Penzilla",
				"license": "PENZILLA DESIGN, STANDARD LICENCE",
				"note": "Graphics created by Penzilla Design in addition to assetes created by the authors mentioned in this document",
				"links": ["https://penzilla.itch.io/top-down-retro-interior"],
			},
			{
				"name": "Private Investigator Office Asset Pack",
				"creator": "kypixel",
				"license": "Custom Itch.io License (Commercial / Attribution Required)",
				"note": "",
				"links": ["https://devotedloner.itch.io/private-investigator-office-asset-pack"],
			},
			{
				"name": "Retro Interior Expansion Pack (16×16)",
				"creator": "Syntaxes of Play",
				"license": "CC0",
				"note": "",
				"links": ["https://synofplay.itch.io/retro-interior-expansion-pack-1616"],
			},
			{
				"name": "Balcony Garden tile set",
				"creator": "SeasideSnowman",
				"license": "CC BY-ND 4.0",
				"note": "",
				"links": ["https://seasidesnowman.itch.io/balcony-garden"],
			},
			{
				"name": "Free Office Pixel Art",
				"creator": "Arlan_TR",
				"license": "Custom Itch.io License",
				"note": "",
				"links": ["https://arlantr.itch.io/free-office-pixel-art"],
			},
		],
	},
	{
		"title": "Characters",
		"entries": [
			{
				"name": "head/heads/human/male",
				"creator": "bluecarrot16, Benjamin K. Smith (BenCreating), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-character-bases"],
			},
			{
				"name": "shadow/adult",
				"creator": "drjamgo@hotmail.com (Dr. Jamgo), JaidynReiman",
				"license": "CC0",
				"note": "LPC generator asset. CC0, no attribution required (credited as a courtesy).",
				"links": ["https://opengameart.org/content/shadow-for-lpc-sprite"],
			},
			{
				"name": "body/bodies/female",
				"creator": "Benjamin K. Smpith (BenCreating), bluecarrot16, TheraHedwig, Evert, MuffinElZangano, Durrani, Pierre Vigier (pvigier), ElizaWy, Matthew Krohn (makrohn), Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "https://opengameart.org/content/lpc-ladies", "https://opengameart.org/content/lpc-7-womens-shirts", "https://opengameart.org/content/lpc-jump-expanded", "https://opengameart.org/content/lpc-be-seated", "https://opengameart.org/content/lpc-revised-character-basics", "https://gitlab.com/vagabondgame/lpc-characters", "https://opengameart.org/content/lpc-male-jumping-animation-by-durrani", "https://opengameart.org/content/lpc-runcycle-and-diagonal-walkcycle"],
			},
			{
				"name": "eyes/eyebrows/thin",
				"creator": "ElizaWy",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Hair", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more"],
			},
			{
				"name": "head/faces/male/shock",
				"creator": "JaidynReiman, ElizaWy, Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Head", "https://opengameart.org/content/ulpc-expanded-expressions"],
			},
			{
				"name": "head/nose/button",
				"creator": "Thane Brimhall (pennomi), laetissima, Matthew Krohn (makrohn)",
				"license": "GPL 3.0, CC-BY-SA 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-base-character-expressions"],
			},
			{
				"name": "hair/long_center_part",
				"creator": "thecilekli, bluecarrot16",
				"license": "CC0",
				"note": "LPC generator asset. CC0, no attribution required (credited as a courtesy).",
				"links": ["https://opengameart.org/content/lpc-long-straight-hair-with-12-colors", "https://opengameart.org/content/lpc-hair"],
			},
			{
				"name": "torso/clothes/shortsleeve/tshirt_scoop (female)",
				"creator": "ElizaWy, JaidynReiman, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["http://opengameart.org/content/lpc-revised-character-basics", "https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more", "https://opengameart.org/content/lpc-expanded-simple-shirts"],
			},
			{
				"name": "legs/pants/thin",
				"creator": "bluecarrot16, JaidynReiman, ElizaWy, Joe White, Matthew Krohn (makrohn), Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, GPL 3.0, CC-BY-SA 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "http://opengameart.org/content/lpc-clothing-updates", "https://opengameart.org/content/lpc-expanded-pants"],
			},
			{
				"name": "feet/shoes/ghillies/thin",
				"creator": "bluecarrot16, JaidynReiman, Thane Brimhall (pennomi), laetissima, Matthew Krohn (makrohn)",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-2-characters", "http://opengameart.org/content/lpc-clothing-updates", "https://opengameart.org/content/lpc-expanded-socks-shoes"],
			},
			{
				"name": "tools/hoe",
				"creator": "bluecarrot16, JaidynReiman, Pierre Vigier (pvigier), Johannes Sjölund (wulax), Inboxninja",
				"license": "CC-BY-SA 3.0",
				"note": "LPC generator asset. CC-BY-SA 3.0 only: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-hand-tools"],
			},
			{
				"name": "body/bodies/male",
				"creator": "bluecarrot16, JaidynReiman, Benjamin K. Smith (BenCreating), Evert, Eliza Wyatt (ElizaWy), TheraHedwig, MuffinElZangano, Durrani, Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "https://opengameart.org/content/lpc-male-jumping-animation-by-durrani", "https://opengameart.org/content/lpc-runcycle-and-diagonal-walkcycle", "https://opengameart.org/content/lpc-revised-character-basics", "https://opengameart.org/content/lpc-be-seated", "https://opengameart.org/content/lpc-runcycle-for-male-muscular-and-pregnant-character-bases-with-modular-heads", "https://opengameart.org/content/lpc-jump-expanded", "https://opengameart.org/content/lpc-character-bases"],
			},
			{
				"name": "head/heads/human/male_small",
				"creator": "ElizaWy, Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, CC-BY",
				"note": "LPC generator asset. No link in generator credits (original head: Redshrike, reduced size by ElizaWy). Can be used under OGA-BY 3.0; the CC-BY version is not specified.",
				"links": [],
			},
			{
				"name": "head/nose/elderly",
				"creator": "ElizaWy",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/lpc-revised-elders"],
			},
			{
				"name": "eyes/eyebrows/thick",
				"creator": "ElizaWy",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Hair", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more"],
			},
			{
				"name": "hair/cowlick",
				"creator": "ElizaWy, bluecarrot16",
				"license": "CC0",
				"note": "LPC generator asset. CC0, no attribution required (credited as a courtesy).",
				"links": ["https://opengameart.org/content/lpc-hair", "https://github.com/ElizaWy/LPC/blob/main/Characters/Hair", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more"],
			},
			{
				"name": "legs/pants (male)",
				"creator": "bluecarrot16, JaidynReiman, ElizaWy, Matthew Krohn (makrohn), Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, GPL 3.0, CC-BY-SA 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "https://opengameart.org/content/lpc-expanded-pants"],
			},
			{
				"name": "torso/clothes/shortsleeve/tshirt_buttoned (male)",
				"creator": "ElizaWy, JaidynReiman, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["http://opengameart.org/content/lpc-revised-character-basics", "https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more", "https://opengameart.org/content/lpc-expanded-simple-shirts"],
			},
			{
				"name": "beards/beard/trimmed",
				"creator": "ElizaWy",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Hair", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more"],
			},
			{
				"name": "head/faces/male/shame",
				"creator": "JaidynReiman, ElizaWy, Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Head", "https://opengameart.org/content/ulpc-expanded-expressions"],
			},
			{
				"name": "hair/parted2",
				"creator": "Skorpio, bluecarrot16",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-skorpios-scifi-sprite-pack", "https://opengameart.org/content/lpc-hair"],
			},
			{
				"name": "legs/formal (male)",
				"creator": "bluecarrot16, JaidynReiman, ElizaWy, Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "https://opengameart.org/content/lpc-2-characters", "https://opengameart.org/content/lpc-gentleman", "https://opengameart.org/content/lpc-expanded-pants"],
			},
			{
				"name": "feet/socks/ankle (male)",
				"creator": "JaidynReiman, ElizaWy, Bluecarrot16, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-socks-shoes"],
			},
			{
				"name": "feet/shoes/revised (male)",
				"creator": "JaidynReiman, ElizaWy, Bluecarrot16, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-socks-shoes"],
			},
			{
				"name": "torso/clothes/longsleeve/longsleeve2_polo (male)",
				"creator": "ElizaWy, JaidynReiman, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["http://opengameart.org/content/lpc-revised-character-basics", "https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more", "https://opengameart.org/content/lpc-expanded-simple-shirts"],
			},
			{
				"name": "arms/hands/gloves (male)",
				"creator": "Michael Whitlock (bigbeargames), Matthew Krohn (makrohn), Johannes Sjölund (wulax), bluecarrot16, JaidynReiman",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "http://opengameart.org/content/lpc-clothing-updates"],
			},
			{
				"name": "head/faces/global/sad2",
				"creator": "JaidynReiman, Thane Brimhall (pennomi), laetissima, Stephen Challener (Redshrike)",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-base-character-expressions", "https://opengameart.org/content/ulpc-expanded-expressions"],
			},
			{
				"name": "beards/beard/5oclock_shadow",
				"creator": "JaidynReiman, Thane Brimhall (pennomi), laetissima",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-base-character-expressions"],
			},
			{
				"name": "hair/bedhead",
				"creator": "JaidynReiman, Manuel Riecke (MrBeast)",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/liberated-pixel-cup-lpc-base-assets-sprites-map-tiles", "https://opengameart.org/content/lpc-expanded-hair"],
			},
			{
				"name": "torso/clothes/shortsleeve/tshirt_vneck (male)",
				"creator": "ElizaWy, JaidynReiman, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/lpc-revised-character-basics", "https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more", "https://opengameart.org/content/lpc-expanded-simple-shirts"],
			},
			{
				"name": "legs/shorts/shorts (male)",
				"creator": "JaidynReiman, ElizaWy, Bluecarrot16, Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-pants"],
			},
			{
				"name": "head/faces/male/anger",
				"creator": "JaidynReiman, ElizaWy, Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://github.com/ElizaWy/LPC/tree/main/Characters/Head", "https://opengameart.org/content/ulpc-expanded-expressions"],
			},
			{
				"name": "legs/pantaloons (male)",
				"creator": "Nila122, JaidynReiman, Johannes Sjölund (wulax), Stephen Challener (Redshrike)",
				"license": "OGA-BY 3.0, GPL 2.0, GPL 3.0, CC-BY-SA 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["https://opengameart.org/content/lpc-pirates", "https://opengameart.org/content/more-lpc-clothes-and-hair", "https://opengameart.org/content/lpc-expanded-pants"],
			},
			{
				"name": "torso/clothes/longsleeve/longsleeve2_cardigan (male)",
				"creator": "ElizaWy, JaidynReiman, Stephen Challener (Redshrike), Johannes Sjölund (wulax)",
				"license": "OGA-BY 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["http://opengameart.org/content/lpc-revised-character-basics", "https://github.com/ElizaWy/LPC/tree/main/Characters/Clothing", "https://opengameart.org/content/lpc-expanded-sit-run-jump-more", "https://opengameart.org/content/lpc-expanded-simple-shirts"],
			},
			{
				"name": "beards/mustache/basic",
				"creator": "JaidynReiman, Carlo Enrico Victoria (Nemisys)",
				"license": "CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Dual-licensed (CC-BY-SA 3.0 / GPL 3.0), no OGA-BY option: share-alike applies to this asset and any modified versions.",
				"links": ["https://opengameart.org/content/lpc-brunet-mustache"],
			},
			{
				"name": "hat/cloth/hood",
				"creator": "Johannes Sjölund (wulax), JaidynReiman",
				"license": "OGA-BY 3.0, CC-BY-SA 3.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0. Original black/white recolors credited to an unknown author ('??') in the generator credits.",
				"links": ["https://opengameart.org/content/lpc-medieval-fantasy-character-sprites", "https://opengameart.org/content/lpc-expanded-hats-facial-helmets"],
			},
			{
				"name": "feet/shoes/sara (male)",
				"creator": "JaidynReiman, Bluecarrot16, Mandi Paugh, Stephen Challener (Redshrike), William.Thompsonj",
				"license": "OGA-BY 3.0, CC-BY 3.0+, GPL 2.0, GPL 3.0",
				"note": "LPC generator asset. Multi-licensed: can be used under OGA-BY 3.0 (attribution only).",
				"links": ["http://opengameart.org/content/sara-wizard", "https://opengameart.org/content/lpc-sara", "https://opengameart.org/content/lpc-expanded-socks-shoes"],
			},
		],
	},
	{
		"title": "Items & Props",
		"entries": [
			{
				"name": "Free Tools Asset (16x16)",
				"creator": "DantePixels",
				"license": "Custom Itch.io License (Commercial / Credit Required)",
				"note": "Creator's Twitter page:https://x.com/Pixelahead",
				"links": ["https://dantepixels.itch.io/key-items-16x16"],
			},
			{
				"name": "Pixel art illustration Flashlight",
				"creator": "Collaborapix Studio",
				"license": "Custom Free license (Attribution Required)",
				"note": "",
				"links": ["https://www.vecteezy.com/vector-art/35553473-pixel-art-illustration-flashlight-pixelated-flashlight-flashlight-pixelated-for-the-pixel-art-game-and-icon-for-website-and-video-game-old-school-retro"],
			},
			{
				"name": "Crowbar & clue scribble",
				"creator": "PixeLab used by Muhammed Turhan",
				"license": "Open RAIL-M license",
				"note": "",
				"links": ["https://www.pixellab.ai/"],
			},
		],
	},
	{
		"title": "Sound Effects",
		"entries": [
			{
				"name": "Fireplace rumble",
				"creator": "LukaCafuka",
				"license": "CC0",
				"note": "",
				"links": ["https://freesound.org/people/LukaCafuka/sounds/783660/"],
			},
			{
				"name": "The Fireplace 3.wav",
				"creator": "NoOneIsReal",
				"license": "CC0",
				"note": "",
				"links": ["https://freesound.org/people/NoOneIsReal/sounds/387128/"],
			},
			{
				"name": "kitchen sink on loop",
				"creator": "Hexenv88",
				"license": "CC0",
				"note": "",
				"links": ["https://freesound.org/people/Hexenv88/sounds/731600/"],
			},
			{
				"name": "Broken Record Player Playing Record",
				"creator": "TheEpicFaceManBFY",
				"license": "CC0",
				"note": "",
				"links": ["https://freesound.org/people/TheEpicFaceManBFY/sounds/716284/"],
			},
			{
				"name": "Cheesy morning news tune",
				"creator": "Tuben",
				"license": "CC0",
				"note": "",
				"links": ["https://freesound.org/people/Tuben/sounds/272044/"],
			},
		],
	},
	{
		"title": "Music",
		"entries": [
			{
				"name": "This House",
				"creator": "Kevin MacLeod",
				"license": "Creative Commons: By Attribution 4.0",
				"note": "\"This House\" Kevin MacLeod (incompetech.com)",
				"links": ["https://incompetech.com/music/royalty-free/music.html"],
			},
		],
	},
]
